"""
Django settings for stm_site project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import access

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(SITE_ROOT, ...)
SITE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# SITE_ROOT = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = access.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['localhost', '0.0.0.0', '127.0.0.1', '192.168.43.38', 'studiomaneken.com', '92.53.97.160', 'maneken.studio']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',

    'sorl.thumbnail',
    'sitetree',
    'tinymce',
    'filebrowser',
    'content_gallery',

    # apps
    'stm_site',
    # 'polls',
    'theatre',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'stm_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SITE_ROOT, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
            # 'loaders': [
            #     ('django.template.loaders.cached.Loader', [
            #         'django.template.loaders.filesystem.Loader',
            #         'django.template.loaders.theatre.Loader',
            #     ]),
            # ],
        },
    },
]

WSGI_APPLICATION = 'stm_site.wsgi.application'


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(SITE_ROOT, 'tmp') +  '/debug.log',
#         },
#     },
#     'loggers': {
#         'logfile': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(SITE_ROOT, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'u0630501_default',
#         'USER': 'u0630501_default',
#         'PASSWORD': '1E0h0H5j',
#         'HOST': 'localhost',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

# A list of directories where Django looks for translation files
LOCALE_PATHS = [
    os.path.join(SITE_ROOT, 'locale'),
]

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-ru'
LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
]
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = '/'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

SITE_ID = 2

STATICFILES_DIRS = [
    os.path.join(SITE_ROOT, "static"),
    os.path.join(SITE_ROOT, "media")
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(SITE_ROOT, 'collectedstatic')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(SITE_ROOT, "media")

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other
    # 'compressor.finders.CompressorFinder',
]

# FILEBROWSER_DIRECTORY = 'uploads/'
# FILEBROWSER_EXTENSIONS = {
#     'Image': ['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff'],
#     'Document': ['.pdf', '.doc', '.rtf', '.txt', '.xls', '.csv'],
#     'Video': ['.mov', '.wmv', '.mpeg', '.mpg', '.avi', '.rm'],
#     'Audio': ['.mp3', '.mp4', '.wav', '.aiff', '.midi', '.m4p']
# }

# DIRECTORY = ''

# TINYMCE DEFAULT CONFIG
TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 960,
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'modern',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}

CONTENT_GALLERY = {
}

# EMAIL
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'unifest@maneken.studio'
EMAIL_HOST_PASSWORD = access.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# Deploy 

# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_SECONDS = 1
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# X_FRAME_OPTIONS = 'DENY'
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# CSRF_COOKIE_SECURE = True
