# Generated by Django 2.1.1 on 2018-09-24 11:09

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spectacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(verbose_name='description')),
                ('premiere_date', models.DateTimeField(default=datetime.datetime(2018, 9, 24, 16, 9, 27, 363972), verbose_name='Дата премьеры')),
                ('is_premiere', models.BooleanField(default=False)),
            ],
        ),
    ]
