# Generated by Django 2.1.1 on 2018-09-28 12:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spectacles',
            field=models.ManyToManyField(blank=True, to='theatre.Spectacle', verbose_name='Спектакли'),
        ),
        migrations.AlterField(
            model_name='role',
            name='artists',
            field=models.ManyToManyField(blank=True, to='theatre.Artist', verbose_name='Студийцы'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='close_date',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), verbose_name='Дата закрытия спектакля'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='is_premiere',
            field=models.BooleanField(blank=True, default=False, verbose_name='Премьера?'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='premiere_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата премьеры'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='rating_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Голосов "Не понравилось"'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='rating_yes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Голосов "Понравилось"'),
        ),
    ]
