# Generated by Django 2.1.1 on 2018-09-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_auto_20180928_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacle',
            name='artists',
            field=models.ManyToManyField(blank=True, to='theatre.Artist', verbose_name='Артисты'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Genre', verbose_name='Жанр'),
        ),
    ]
