# Generated by Django 2.1.1 on 2018-09-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_auto_20180928_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectacle',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.Genre', verbose_name='Жанр'),
        ),
    ]
