# Generated by Django 2.1.1 on 2018-09-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_auto_20180928_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectacle',
            name='genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='theatre.Genre', verbose_name='Жанр'),
        ),
    ]
