# Generated by Django 2.1.1 on 2018-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_remove_artist_spectacles'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='artist',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Публиковать?'),
        ),
        migrations.AddField(
            model_name='genre',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='genre',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Публиковать?'),
        ),
        migrations.AddField(
            model_name='role',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='role',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Публиковать?'),
        ),
        migrations.AddField(
            model_name='spectacle',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='spectacle',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Публиковать?'),
        ),
    ]
