# Generated by Django 2.1.1 on 2018-09-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_auto_20180928_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['position', 'last_name'], 'verbose_name': 'Студиец', 'verbose_name_plural': 'Труппа'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='spectacle',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли'},
        ),
    ]
