# Generated by Django 2.1.1 on 2018-09-29 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0009_auto_20180929_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('publication', models.BooleanField(default=True, verbose_name='Публиковать?')),
                ('event_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата события')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Комментарий к событию')),
            ],
            options={
                'verbose_name': 'Афиша',
                'verbose_name_plural': 'Афиша',
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Студиец', 'verbose_name_plural': 'Труппа'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='spectacle',
            options={'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли'},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='spectacles',
            new_name='spectacle',
        ),
        migrations.AddField(
            model_name='afisha',
            name='spectacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Spectacle', verbose_name='Событие'),
        ),
    ]
