# Generated by Django 2.1.1 on 2018-09-29 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0010_auto_20180929_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afisha',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'Афиша'},
        ),
        migrations.AlterField(
            model_name='afisha',
            name='event_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата события'),
        ),
    ]
