# Generated by Django 2.1.1 on 2018-10-01 15:30

from django.db import migrations, models
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0011_auto_20180929_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afisha',
            options={'ordering': ['event_date'], 'verbose_name': 'Событие', 'verbose_name_plural': 'Афиша'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['last_name'], 'verbose_name': 'Студиец', 'verbose_name_plural': 'Труппа'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['spectacle'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='spectacle',
            options={'ordering': ['name'], 'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли'},
        ),
        migrations.AlterField(
            model_name='afisha',
            name='event_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Аватар'),
        ),
    ]
