# Generated by Django 2.1.1 on 2018-10-04 08:30

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0012_auto_20181001_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afisha',
            old_name='spectacle',
            new_name='event',
        ),
        migrations.AddField(
            model_name='afisha',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Фото афиши'),
        ),
        migrations.AddField(
            model_name='genre',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Фото жанра'),
        ),
        migrations.AddField(
            model_name='role',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Фото роли'),
        ),
        migrations.AddField(
            model_name='spectacle',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Главное фото'),
        ),
    ]
