# Generated by Django 2.1.1 on 2018-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20181011_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
