# Generated by Django 2.1.1 on 2018-10-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20181011_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='publication',
        ),
    ]
