# Generated by Django 2.1.1 on 2018-10-11 09:50

from django.db import migrations, models
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20181011_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=400, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name="Menu item's photo"),
        ),
        migrations.AddField(
            model_name='menu',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Публиковать?'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=400, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name="Menu item's photo"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Публиковать?'),
        ),
    ]
